adadelta_rho: 0.95
adagrad_initial_accumulator_value: 0.1
adam_beta1: 0.9
adam_beta2: 0.999
backup_measure: null
batch_size: 8
checkpoint_exclude_scopes: null
checkpoint_path: null
clone_on_cpu: false
curriculum: true
dataset_dir: E:\Thesis\data\cifar10\train
dataset_name: cifar10
dataset_split_name: train
end_learning_rate: 0.0001
ftrl_initial_accumulator_value: 0.1
ftrl_l1: 0.0
ftrl_l2: 0.0
ftrl_learning_rate_power: -0.5
id: !!python/object:uuid.UUID
  int: 50972492003520110594912260599598065565
  is_safe: !!python/object/apply:uuid.SafeUUID
  - null
ignore_missing_vars: false
label_smoothing: 0.0
labels_offset: 0
learning_rate: 0.01
learning_rate_decay_factor: 0.94
learning_rate_decay_type: exponential
log_every_n_steps: 10
master: null
max_number_of_steps: 100000
measure: null
measure_list: kl,mi,iv,ssim,psnr,l1,l2,cross_entropy
model_name: inception_v1
momentum: 0.9
moving_average_decay: null
name: cifar10_config
num_clones: 1
num_epochs_per_decay: 2.0
num_preprocessing_threads: 4
num_ps_tasks: 0
num_readers: 8
opt_epsilon: 1.0
optimizer: sgd
ordering: 0
patch_size: null
preprocessing_name: null
purpose: null
replicas_to_aggregate: 1
rmsprop_decay: 0.9
rmsprop_momentum: 0.9
save_interval_secs: 300
save_summaries_secs: 600
sync_replicas: false
task: 0
tf_master: null
train_image_size: 224
trainable_scopes: null
training_log_dir: E:\Thesis\logs
weight_decay: 4.0e-05
worker_replicas: 1
